#!/bin/sh

CURRENT=$(goal node status -d /var/lib/algorand | awk 'FNR == 1 {print $4}')

EXPIRING=$(sudo goal account listpartkeys -d /var/lib/algorand | \
    awk 'FNR == 2 { printf "%s", $6 }')

if [ $CURRENT -gt $EXPIRING ]
then
    DAYS=$(( ($CURRENT - $EXPIRING) / 19200 ))
else
    DAYS=$(( ($EXPIRING - $CURRENT) / 19200 ))
fi

BOLD=$(tput bold)

echo "Current round is  $CURRENT"
echo "Expiring round is $EXPIRING"
echo

if [ $CURRENT -gt $EXPIRING ]
then
    echo "The key expired ${BOLD}$DAYS days ago"
else
    echo "The key expires in ${BOLD}$DAYS days"
fi
