#!/bin/bash

echo "Enter input string to be decrypted:"
read -r input_string
echo "Enter decryption password:"
read -rs password

decrypted=$(echo "$input_string" | openssl enc -d -aes-256-cbc  -pbkdf2 -a -salt -pass pass:"$password")

echo "Decrypted string:"
echo "$decrypted"
