#!/bin/bash

echo "Enter input string to be encrypted:"
read input_string
echo "Enter encryption password:"
read -s password

encrypted=$(echo "$input_string" | openssl enc -aes-256-cbc -a -salt -pass pass:"$password")

# transform encrypted to base64 encoded string
encrypted=$(echo "$encrypted" | base64)

echo "Encrypted string:"
echo "$encrypted"
