#!/bin/bash

echo "Enter input string to be encrypted:"
read input_string
echo "Enter encryption password:"
read -s password

encrypted=$(echo "$input_string" | openssl enc -aes-256-cbc -a -A -salt -pass pass:"$password")

echo "Encrypted string:"
echo "$encrypted"
