#!/bin/sh
CURRENT=$(goal node status -d /var/lib/algorand | awk 'FNR == 1 {print $4}')

EXPIRING=$(sudo goal account listpartkeys -d /var/lib/algorand | \
    awk 'FNR == 2 { printf "%s", $5 }')

DAYS=$(( ($EXPIRING - $CURRENT) / 19200 ))

BOLD=$(tput bold)

echo "Current round is  $CURRENT"
echo "Expiring round is $EXPIRING"
echo
echo "The key expires in ${BOLD}$DAYS days"
