#!/usr/bin/env bash

# This script is meant to initialize a new user after their home folder has been created
# A key to access Github, etc. should already be in ~/.ssh; then the script does:
# -> start ssh-agent
# -> install useful software if needed
# -> my dotfiles repo is cloned, symlinks created
# -> my scripts repo is cloned
# -> my neovim repo is cloned

#start ssh-agent to avoid having to input passowrds all the time
if [ ! -f ~/.ssh/id_rsa ] ; then
    echo Please add a private key ~/.ssh/id_rsa for GitHub, etc.
    exit
else
    SSH_ENV="$HOME/.ssh/environment"
    function start_agent {
        echo "Initialising new SSH agent..."
        /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
        echo succeeded
        chmod 600 "${SSH_ENV}"
        . "${SSH_ENV}" > /dev/null
        /usr/bin/ssh-add;
    }
    # Source SSH settings, if applicable
    if [ -f "${SSH_ENV}" ]; then
        . "${SSH_ENV}" > /dev/null
        ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
            start_agent;
        }
    else
        start_agent;
    fi
fi

# install software
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-add-repository ppa:neovim-ppa/stable
sudo apt-get -y install curl git mercurial neovim autojump bash-completion

#get dotfiles repo if needed
if [ ! -d ~/dev/dotfiles/ ] ; then
    mkdir -p ~/dev/dotfiles/
    git clone git@github.com:giuliop/dotfiles.git ~/dev/dotfiles/
    #create symlinks
    cd ~
    ln -sf ~/dev/dotfiles/.bash_profile
    ln -sf ~/dev/dotfiles/.bashrc
    ln -sf ~/dev/dotfiles/.inputrc
    ln -sf ~/dev/dotfiles/.tmux.conf
    ln -sf ~/dev/dotfiles/.gitconfig
    #delete old files
    if [ -f ~/.profile ] ; then
        rm ~/.profile
    fi
    echo -e "\n***\nPlease run . ~/.bash_profile to load the new configuration\n***\n"
fi

#get my scripts repo if needed
if [ ! -d ~/dev/scripts/ ] ; then
    mkdir -p ~/dev/scripts/
    git clone git@github.com:giuliop/utility-scripts.git ~/dev/scripts/
fi

#get neovim repo if needed
if [ ! -d /home/gws/.config/nvim ] ; then
    mkdir -p /home/gws/.config/nvim
    git clone git@github.com:giuliop/nvim.git /home/gws/.config/nvim
    #get plug.vim to manage plug-ins
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

