#!/usr/bin/env bash

# list of git repo to update
git_dirs=(
    ~/dev/dotfiles
    ~/dev/scripts
    ~/dev/sicp
    ~/.vim
    ~/.emacs.d
    ~/dev/clojure/lib/gws
    )

# for each dir git pull and push
for dir in ${git_dirs[@]}; do
    echo
    echo "processing "$dir
    cd $dir
    git status
    git pull
    git push
done

