#!/usr/bin/env bash

### This script synchs a bunch of git repos ###

# dict with local dirs as keys and remote repos as values
declare -A git_dirs=(
   ["$HOME/dev/dotfiles"]="git@github.com:giuliop/dotfiles.git" 
   #["$HOME/dev/sicp"]="git@github.com:giuliop/sicp.git"
   ["$HOME/dev/clojure/ai"]="git@github.com:giuliop/AI-modern-approach-3e.git"
   ["$HOME/dev/scripts"]="git@github.com:giuliop/utility-scripts.git"
   ["$HOME/.config/nvim"]="git@github.com:giuliop/nvim.git"
   ["$HOME/dev/clojure/lib/gws"]="git@github.com:giuliop/clojure-mylib.git"
)

# for each dir
for dir in "${!git_dirs[@]}"; do
    echo
    echo "processing $dir"

    # if no git repo create it
    if [ ! -d "$dir/.git/" ]; then
        echo "Repo not found: $dir/.git/"
        mkdir -p "$dir"
        git clone "${git_dirs[$dir]}" "$dir"

    # else git pull and push
    else
        cd "$dir"
        git status
        git pull
        git push
    fi
done

