#!/usr/bin/env bash

# the name of tmux session
SESSION="sicp"_$USER

# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    sleep 1
    tmux -2 attach -t $SESSION
    exit 0;
fi

# create a new session, named $SESSION, and detach from it
tmux new-session -d -s $SESSION -n 'sicp' 'vim ~/dev/sicp/4.scm;bash -i'

# populate the windows you want
tmux split-window -h -t $SESSION:1 'gsi ~/dev/sicp/4.scm -;bash -i'
tmux new-window -t $SESSION

# all done. select starting window and get to work
tmux select-window -t $SESSION:1
tmux -2 attach -t $SESSION
